version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sales_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - sales_network

  nginx:
    image: nginx:alpine
    container_name: sales_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - sales_network

  mysql:
    image: mysql:8.0
    container_name: sales_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_db
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - sales_network

  redis:
    image: redis:alpine
    container_name: sales_redis
    ports:
      - "6379:6379"
    networks:
      - sales_network

  frontend:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - sales_network

networks:
  sales_network:
    driver: bridge